language: java
jdk:
  - openjdk8
services:
  - mongodb
  - elasticsearch
install: true
script: ./gradlew test
branches:
  only:
    - master
before_install:
  - mysql -e 'CREATE DATABASE tracklines;'
