version: '3'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    ports:
      - 9200:9200
      - 9300:9300
  database:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: hibernate
    ports:
      - 3306:3306

#  backend:
#    build:
#      context: ./build/bundle
#    ports:
#      - 8080:8080
